[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
<<<<<<< HEAD
  package = "@netlify/plugin-nextjs"
=======
  package = "@netlify/plugin-nextjs"
>>>>>>> 5a42823 (feat: netlify prodn)
